### ISSUE TITLE
大佬笔记是我目前见过最好的，但是后面第六周开始的笔记就没有了，请问有更新的打算吗

### ISSUE THREAD

**Issue by unravelZ** [scruel/ML-AndrewNg-Notes#7]

**Comment by scruel** [comment]
有计划的，不过博客优先级会更高些，另外工作以后有点内耗，可能还要调整调整才会开始，建议你可以先接着学，同时欢迎 fork。

**Comment by unravelZ** [comment]
> 有计划的，不过博客优先级会更高些，另外工作以后有点内耗，可能还要调整调整才会开始，建议你可以先接着学，同时欢迎 fork。
明白了，感谢大佬的贡献，你已经很强了
